version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "4f:90:3a:07:a5:a5:4b:9e:cb:50:d7:cd:dd:eb:b1:c9T"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: cd frontend && npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: cd frontend && npm run build
      - run:
          name: Istall rsync
          command: sudo apt-get update && sudo apt install -y rsync
      - run:
          name: Copy to server
          command: rsync -av frontend/dist/ $PROD_USER@$PROD_SERVER:/var/www/barcode