version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4f:90:3a:07:a5:a5:4b:9e:cb:50:d7:cd:dd:eb:b1:c9T"
      - run:
          command: "deploy.sh"