version: 2
jobs:
  build:
    working_directory: ~/barcode-playround
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - node_modules
      - run:
          name: Build the application
          command: npm run build